---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.services.serviceName }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.services.serviceName }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.serviceName }} 
    spec:
      containers:
      - name: {{ .Values.services.serviceName }}
        image: {{ .Values.services.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: hub_datasource_url_env
          value: {{ .Values.hub.datasource_url }}
        - name: hub_datasource_username_env
          value: {{ .Values.hub.datasource_username }}
        - name: hub_datasource_password_env
          value: {{ .Values.hub.datasource_password }}
        ports:
        - containerPort: {{ .Values.hub.port }} 
