apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.contactus.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.services.contactus.serviceName }}
    component: {{ .Values.component }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.contactus.serviceName }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.services.contactus.serviceName }}
        component: {{ .Values.component }}
    spec:
      containers:
        - name: {{ .Values.services.contactus.serviceName }}
          image: {{ .Values.services.contactus.dockerImage }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.contactus.containerPort }}
          env:
            - name: SENDRIG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mysendgrid
                  key: sendgridkey

          readinessProbe:
            tcpSocket:
              port: {{ .Values.services.contactus.containerPort }}

